services:
  # Solo Frontend OndAI - Versión simplificada
  ondai-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: ${NODE_ENV}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_APP_CACHE_VERSION: ${VITE_APP_CACHE_VERSION}
        VITE_GA_TRACKING_ID: ${VITE_GA_TRACKING_ID}
        VITE_HOTJAR_ID: ${VITE_HOTJAR_ID}
        VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_APP_VERSION: ${VITE_APP_VERSION}
        VITE_APP_DESCRIPTION: ${VITE_APP_DESCRIPTION}
        VITE_SUPABASE_EDGE_BASE_URL: ${VITE_SUPABASE_EDGE_BASE_URL}
        VITE_META_APP_ID: ${VITE_META_APP_ID}
        VITE_META_APP_SECRET: ${VITE_META_APP_SECRET}
        VITE_META_VERIFY_TOKEN: ${VITE_META_VERIFY_TOKEN}
        VITE_META_GRAPH_VERSION: ${VITE_META_GRAPH_VERSION}
        VITE_SERVICE_ROLE_KEY: ${VITE_SERVICE_ROLE_KEY}
    container_name: ondai-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'