// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eedgojmziiwxodyfzrpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlZGdvam16aWl3eG9keWZ6cnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODM5MjAsImV4cCI6MjA2NTg1OTkyMH0.g4T9keKsr3-I2qF7w6etSb0wDxe0aiFd5fntkrD72P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);